# Copied from http://www.codesqueeze.com/the-ultimate-top-25-chuck-norris-the-programmer-jokes/
# and http://www.reddit.com/r/programming/comments/675jj/richard_stallman_is_the_new_chuck_norris
# and http://chucknorrisfacts.com/
CHUCK_NORRIS_FACTS = [
  "throws exceptions across the room",
  "declares arrays of infinite size, because Chuck Norris knows no bounds",
  "doesn't have disk latency because the hard drive knows to hurry the hell up",
  "writes code that optimizes itself",
  "can't test for equality because he has no equal",
  "doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick()",
  "'s first program was \"kill -9\"",
  "burst the dot com bubble",
  "can write infinite recursion functions... and have them return",
  "can solve the Towers of Hanoi in one move",
  "finished World of Warcraft",
  "doesn't use web standards as the web will conform to him",
  "doesn't do Burn Down charts. He does Smack Down charts.",
  "can delete the Recycling Bin",
  "'s beard can type 140 wpm",
  "can unit test entire applications with a single assert",
  "doesn't bug hunt. He goes bug killing.",
  "'s keyboard doesn't have a Ctrl key because Chuck Norris is always in control",
  "never gets asked for estimates... ever!",
  "can always say \"It works on my machine\"",
  "knows only one pattern: the God Object",
  "can overflow your stack just by looking at it",
  "doesn't need a debugger. He just stares down the bug until the code confesses.",
  "can access private methods",
  "can instantiate an abstract class",
  "doesn't need the Factory pattern. He can instantiate interfaces directly.",
  "is the parent of the Object class",
  "doesn't use strongly-typed languages. He uses strong languages.",
  "can solve NP-Hard problems in O(1)",
  "knows the last digit of PI",
  "can divide by zero",
  "doesn't get compiler errors. The language changes itself to accommodate Chuck Norris.",
  "'s programs don't have version numbers. He writes them only once.",
  "throws exceptions that can't be caught",
  "doesn't pair program",
  "can write multi-threaded applications with a single thread",
  "doesn't use reflection. Reflection asks politely for his help.",
  "doesn't have an Esc key on his keyboard, because no one escapes Chuck Norris",
  "doesn't delete files. He \"Blows them away\".",
  "can break out of an infinite loop",
  "doesn't use zip files. He just squeezes the hard drive.",
  "can write \"int main();\", compile it, and get a working copy of HURD",
  "can coerce meaningful data from /dev/null",
  "doesn't wget. Chuck Norris wdemands!",
  "can binary search unsorted data",
  "breaks RSA 128-bit encrypted codes in milliseconds",
  "doesn't needs try-catch. Exceptions are too afraid to raise.",
  "can get Visual SourceSafe to actually work",
  "can read all encrypted data, because nothing can hide from Chuck Norris",
  "'s hosting is 101% uptime guaranteed",
  "can access the DB from the UI",
  "'s keyboard has the Any key",
  "can spawn threads that complete before they are started",
  "'s programs do not accept input",
  "can install iTunes without installing QuickTime",
  "doesn't declare variables. He owns them.",
  "doesn't execute transactions. He makes'em pay!",
  "solved the halting problem",
  "doesn't sort. He orders.",
  "doesn't use Oracle. He is the Oracle.",
  "can dereference NULL",
  "'s Eclipse plugin made alien contact",
  "is the ultimate mutex. All threads fear him!",
  "'s test cases cover your code as well'",
  "'s log statements are always at the FATAL level",
  "'s database has only one table, \"Kick\", which he DROPs frequently",
  "'s CSS uses the kick-box-model",
  "gets 9 bits to the byte",
  "can leave neutral or negative feedback on eBay",
  "is the only man who can pronounce GNU the way it is meant to be pronounced",
  "takes notes in binary",
  "gets paid 99 cents by Apple every time he listens to a song",
  "'s iPod came with a real charger instead of just a USB cord",
  "is the reason why Waldo is hiding",
  "can't be found using Google. He finds you.",
  "doesn't cheat death. He wins fair and square.",
  "destroyed the periodic table, because he only recognizes the element of surprise",
  "can kill two stones with one bird",
  "counted to infinity. Twice.",
  "can lead a horse to water AND make it drink",
  "put the laughter in manslaughter",
  "is the only man to ever defeat a brick wall in a game of tennis",
  "doesn't wash his clothes. He disembowels them.",
  "doesn't shower. He takes blood baths.",
  "'s house has no doors, only walls that he walks through",
  "CAN believe it's not butter",
  "always knows the EXACT location of Carmen SanDiego",
  "can touch MC Hammer",
  "played Russian Roulette with a fully loaded gun. And won.",
  "can slam a revolving door",
  "can judge a book by its cover",
  "once kicked a horse in the chin. Its decendants are known today as Giraffes.",
  "once went skydiving, but promised never to do it again. One Grand Canyon is enough.",
  "'s credit cards have no limit. Last weekend, he maxed them out.",
  "crossed the road. No one has ever dared question his motives.",
  "does know what Willis is talking about!",
  "can watch an episode of 60 Minutes in 22 seconds",
  "makes onions cry",
  "is not only a noun, but also a verb",
  "was once in a knife fight, and the knife lost",
  "'s tears cure cancer. Too bad he has never cried.",
  "has already been to Mars. That's why there are no signs of life there.",
  "frequently donates blood to the Red Cross. Just never his own."
]
